# Generated by Django 5.0.3 on 2024-04-25 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='title',
        ),
    ]
